model:
  name: 'model-rijk.h5'
  epochs: 1
  embeddingsize: 256
  optimizers:
    adam:
      learning_rate: 0.1
triplet:
  num_classes_per_batch: 8
  num_images_per_class: 4
image:
  width: 120
  height: 120
  channels: 3
  extension: 'jpeg'
annoy:
  ntrees: 10
augment:
  nsamples: 10000